---
- hosts: all
  name: Required packages
  become: true
  tasks:
    - name: Install git and base-devel
      when: ansible_os_family == 'Debian'
      ansible.builtin.apt:
        state: present
        update_cache: true
        name:
          - git
          - build-essential
    - name: Install git and base-devel
      when: ansible_os_family == 'Archlinux'
      community.general.pacman:
        state: latest
        update_cache: true
        name:
          - base-devel
          - git

- name: Dotfiles
  hosts: all
  roles:
    - 1995parham-me

- name: Message of the day
  become: true
  hosts: all
  tasks:
    - name: Update Message of the Day
      ansible.builtin.template:
        mode: "0644"
        src: templates/motd
        dest: /etc/motd
