Vagrant.require_version ">= 2.0.0"

require 'json'

f = JSON.parse(File.read(File.join(File.dirname(__FILE__), 'config.json')))

Vagrant.configure("2") do |config|
  config.vm.box_check_update = true

  f.each do |g|
    config.vm.define g['name'] do |s|
      s.vm.box = g['box']
      s.vm.hostname = g['name']
      # share current directory in guest machine under path: /vagrant.
      s.vm.synced_folder ".", "/vagrant", disabled: g['no_share']
      s.vm.provider "libvirt" do |lv|
        lv.memory = g['memory']
        lv.cpus = g['cpus']
      end
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.galaxy_role_file = "requirements.yml"
    ansible.verbose = "vv"
  end
end
